---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app-container
          image: nginx:1.27.0-alpine
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html # Path inside the container
      volumes:
        - name: nginx-html
          configMap:
            name: nginx-html-config # ConfigMap name
