---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4-alpine3.20
        ports:
          - name: web
            containerPort: 1337

