---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: lab
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 1337  # Port to access the service
      targetPort: 80  # Port exposed by the container
      # nodePort: 30000  # External node port (optional, or leave for auto-assignment)
  # type: NodePort
